name: "Lint PR"

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        with:
          subjectPattern: ^(?![A-Z]).+[^.]$
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            did not match the configured pattern. Please ensure that the subject
            starts with a lowercase character and does not end with a period.
            
